cp ./a.out.0.2.internalize.bc ./bcFileDir
cp ./a.out.0.0.preopt.bc ./bcFileDir
cp ./a.out.0.5.precodegen.bc ./bcFileDir
cp ./a.out.0.4.opt.bc ./bcFileDir
cp ./src/dircolors.0.0.preopt.bc ./bcFileDir
cp ./src/touch.0.5.precodegen.bc ./bcFileDir
cp ./src/chcon.0.2.internalize.bc ./bcFileDir
cp ./src/od.0.5.precodegen.bc ./bcFileDir
cp ./src/csplit.0.5.precodegen.bc ./bcFileDir
cp ./src/dd.0.0.preopt.bc ./bcFileDir
cp ./src/pinky.0.4.opt.bc ./bcFileDir
cp ./src/ginstall.0.5.precodegen.bc ./bcFileDir
cp ./src/paste.0.0.preopt.bc ./bcFileDir
cp ./src/chcon.0.4.opt.bc ./bcFileDir
cp ./src/chgrp.0.0.preopt.bc ./bcFileDir
cp ./src/comm.0.4.opt.bc ./bcFileDir
cp ./src/link.0.5.precodegen.bc ./bcFileDir
cp ./src/md5sum.0.5.precodegen.bc ./bcFileDir
cp ./src/wc.0.5.precodegen.bc ./bcFileDir
cp ./src/tac.0.2.internalize.bc ./bcFileDir
cp ./src/expand.0.2.internalize.bc ./bcFileDir
cp ./src/id.0.5.precodegen.bc ./bcFileDir
cp ./src/false.0.0.preopt.bc ./bcFileDir
cp ./src/factor.0.4.opt.bc ./bcFileDir
cp ./src/sha224sum.0.5.precodegen.bc ./bcFileDir
cp ./src/seq.0.0.preopt.bc ./bcFileDir
cp ./src/realpath.0.5.precodegen.bc ./bcFileDir
cp ./src/ptx.0.4.opt.bc ./bcFileDir
cp ./src/base64.0.4.opt.bc ./bcFileDir
cp ./src/chmod.0.0.preopt.bc ./bcFileDir
cp ./src/tsort.0.5.precodegen.bc ./bcFileDir
cp ./src/tty.0.0.preopt.bc ./bcFileDir
cp ./src/factor.0.5.precodegen.bc ./bcFileDir
cp ./src/touch.0.0.preopt.bc ./bcFileDir
cp ./src/stdbuf.0.4.opt.bc ./bcFileDir
cp ./src/mkfifo.0.5.precodegen.bc ./bcFileDir
cp ./src/sha512sum.0.0.preopt.bc ./bcFileDir
cp ./src/tee.0.2.internalize.bc ./bcFileDir
cp ./src/df.0.5.precodegen.bc ./bcFileDir
cp ./src/sha224sum.0.4.opt.bc ./bcFileDir
cp ./src/dircolors.0.2.internalize.bc ./bcFileDir
cp ./src/head.0.2.internalize.bc ./bcFileDir
cp ./src/sha512sum.0.2.internalize.bc ./bcFileDir
cp ./src/[.0.4.opt.bc ./bcFileDir
cp ./src/rmdir.0.4.opt.bc ./bcFileDir
cp ./src/yes.0.5.precodegen.bc ./bcFileDir
cp ./src/sum.0.2.internalize.bc ./bcFileDir
cp ./src/users.0.2.internalize.bc ./bcFileDir
cp ./src/truncate.0.5.precodegen.bc ./bcFileDir
cp ./src/cp.0.2.internalize.bc ./bcFileDir
cp ./src/env.0.0.preopt.bc ./bcFileDir
cp ./src/cat.0.2.internalize.bc ./bcFileDir
cp ./src/basename.0.5.precodegen.bc ./bcFileDir
cp ./src/chown.0.0.preopt.bc ./bcFileDir
cp ./src/df.0.4.opt.bc ./bcFileDir
cp ./src/readlink.0.5.precodegen.bc ./bcFileDir
cp ./src/echo.0.4.opt.bc ./bcFileDir
cp ./src/who.0.4.opt.bc ./bcFileDir
cp ./src/nl.0.2.internalize.bc ./bcFileDir
cp ./src/sort.0.4.opt.bc ./bcFileDir
cp ./src/hostid.0.4.opt.bc ./bcFileDir
cp ./src/dir.0.2.internalize.bc ./bcFileDir
cp ./src/sha224sum.0.2.internalize.bc ./bcFileDir
cp ./src/dir.0.4.opt.bc ./bcFileDir
cp ./src/cp.0.0.preopt.bc ./bcFileDir
cp ./src/nl.0.0.preopt.bc ./bcFileDir
cp ./src/dd.0.5.precodegen.bc ./bcFileDir
cp ./src/readlink.0.0.preopt.bc ./bcFileDir
cp ./src/truncate.0.2.internalize.bc ./bcFileDir
cp ./src/unexpand.0.4.opt.bc ./bcFileDir
cp ./src/nice.0.0.preopt.bc ./bcFileDir
cp ./src/md5sum.0.4.opt.bc ./bcFileDir
cp ./src/touch.0.4.opt.bc ./bcFileDir
cp ./src/chroot.0.0.preopt.bc ./bcFileDir
cp ./src/expr.0.4.opt.bc ./bcFileDir
cp ./src/tr.0.5.precodegen.bc ./bcFileDir
cp ./src/fold.0.4.opt.bc ./bcFileDir
cp ./src/uname.0.0.preopt.bc ./bcFileDir
cp ./src/stdbuf.0.5.precodegen.bc ./bcFileDir
cp ./src/shred.0.5.precodegen.bc ./bcFileDir
cp ./src/csplit.0.4.opt.bc ./bcFileDir
cp ./src/mktemp.0.5.precodegen.bc ./bcFileDir
cp ./src/sha384sum.0.5.precodegen.bc ./bcFileDir
cp ./src/sha512sum.0.4.opt.bc ./bcFileDir
cp ./src/wc.0.2.internalize.bc ./bcFileDir
cp ./src/unexpand.0.0.preopt.bc ./bcFileDir
cp ./src/pathchk.0.4.opt.bc ./bcFileDir
cp ./src/sort.0.0.preopt.bc ./bcFileDir
cp ./src/sha1sum.0.2.internalize.bc ./bcFileDir
cp ./src/numfmt.0.5.precodegen.bc ./bcFileDir
cp ./src/sha384sum.0.4.opt.bc ./bcFileDir
cp ./src/false.0.2.internalize.bc ./bcFileDir
cp ./src/ls.0.0.preopt.bc ./bcFileDir
cp ./src/ptx.0.0.preopt.bc ./bcFileDir
cp ./src/basename.0.0.preopt.bc ./bcFileDir
cp ./src/mkdir.0.2.internalize.bc ./bcFileDir
cp ./src/stat.0.2.internalize.bc ./bcFileDir
cp ./src/seq.0.2.internalize.bc ./bcFileDir
cp ./src/split.0.5.precodegen.bc ./bcFileDir
cp ./src/chgrp.0.4.opt.bc ./bcFileDir
cp ./src/dir.0.0.preopt.bc ./bcFileDir
cp ./src/shred.0.0.preopt.bc ./bcFileDir
cp ./src/tty.0.5.precodegen.bc ./bcFileDir
cp ./src/join.0.0.preopt.bc ./bcFileDir
cp ./src/realpath.0.4.opt.bc ./bcFileDir
cp ./src/echo.0.5.precodegen.bc ./bcFileDir
cp ./src/users.0.5.precodegen.bc ./bcFileDir
cp ./src/printenv.0.4.opt.bc ./bcFileDir
cp ./src/mkfifo.0.2.internalize.bc ./bcFileDir
cp ./src/make-prime-list.0.2.internalize.bc ./bcFileDir
cp ./src/stat.0.0.preopt.bc ./bcFileDir
cp ./src/cksum.0.5.precodegen.bc ./bcFileDir
cp ./src/echo.0.0.preopt.bc ./bcFileDir
cp ./src/sleep.0.2.internalize.bc ./bcFileDir
cp ./src/kill.0.5.precodegen.bc ./bcFileDir
cp ./src/cut.0.5.precodegen.bc ./bcFileDir
cp ./src/mktemp.0.0.preopt.bc ./bcFileDir
cp ./src/users.0.0.preopt.bc ./bcFileDir
cp ./src/false.0.5.precodegen.bc ./bcFileDir
cp ./src/mkdir.0.4.opt.bc ./bcFileDir
cp ./src/tr.0.0.preopt.bc ./bcFileDir
cp ./src/who.0.2.internalize.bc ./bcFileDir
cp ./src/mv.0.2.internalize.bc ./bcFileDir
cp ./src/realpath.0.0.preopt.bc ./bcFileDir
cp ./src/readlink.0.4.opt.bc ./bcFileDir
cp ./src/sha512sum.0.5.precodegen.bc ./bcFileDir
cp ./src/unexpand.0.5.precodegen.bc ./bcFileDir
cp ./src/yes.0.2.internalize.bc ./bcFileDir
cp ./src/chown.0.2.internalize.bc ./bcFileDir
cp ./src/shuf.0.0.preopt.bc ./bcFileDir
cp ./src/mkdir.0.0.preopt.bc ./bcFileDir
cp ./src/getlimits.0.5.precodegen.bc ./bcFileDir
cp ./src/stty.0.2.internalize.bc ./bcFileDir
cp ./src/hostid.0.0.preopt.bc ./bcFileDir
cp ./src/od.0.2.internalize.bc ./bcFileDir
cp ./src/mktemp.0.4.opt.bc ./bcFileDir
cp ./src/make-prime-list.0.0.preopt.bc ./bcFileDir
cp ./src/mkfifo.0.4.opt.bc ./bcFileDir
cp ./src/seq.0.5.precodegen.bc ./bcFileDir
cp ./src/split.0.0.preopt.bc ./bcFileDir
cp ./src/uniq.0.4.opt.bc ./bcFileDir
cp ./src/sleep.0.5.precodegen.bc ./bcFileDir
cp ./src/stdbuf.0.2.internalize.bc ./bcFileDir
cp ./src/nohup.0.5.precodegen.bc ./bcFileDir
cp ./src/stty.0.5.precodegen.bc ./bcFileDir
cp ./src/id.0.4.opt.bc ./bcFileDir
cp ./src/uptime.0.5.precodegen.bc ./bcFileDir
cp ./src/cut.0.4.opt.bc ./bcFileDir
cp ./src/logname.0.0.preopt.bc ./bcFileDir
cp ./src/mkdir.0.5.precodegen.bc ./bcFileDir
cp ./src/fmt.0.2.internalize.bc ./bcFileDir
cp ./src/whoami.0.0.preopt.bc ./bcFileDir
cp ./src/make-prime-list.0.5.precodegen.bc ./bcFileDir
cp ./src/tee.0.5.precodegen.bc ./bcFileDir
cp ./src/uptime.0.2.internalize.bc ./bcFileDir
cp ./src/wc.0.0.preopt.bc ./bcFileDir
cp ./src/pinky.0.0.preopt.bc ./bcFileDir
cp ./src/pr.0.0.preopt.bc ./bcFileDir
cp ./src/printenv.0.5.precodegen.bc ./bcFileDir
cp ./src/link.0.4.opt.bc ./bcFileDir
cp ./src/expr.0.5.precodegen.bc ./bcFileDir
cp ./src/paste.0.4.opt.bc ./bcFileDir
cp ./src/sha256sum.0.0.preopt.bc ./bcFileDir
cp ./src/ginstall.0.2.internalize.bc ./bcFileDir
cp ./src/test.0.0.preopt.bc ./bcFileDir
cp ./src/dirname.0.2.internalize.bc ./bcFileDir
cp ./src/tee.0.0.preopt.bc ./bcFileDir
cp ./src/chgrp.0.5.precodegen.bc ./bcFileDir
cp ./src/nproc.0.2.internalize.bc ./bcFileDir
cp ./src/sha256sum.0.4.opt.bc ./bcFileDir
cp ./src/groups.0.4.opt.bc ./bcFileDir
cp ./src/du.0.5.precodegen.bc ./bcFileDir
cp ./src/csplit.0.2.internalize.bc ./bcFileDir
cp ./src/yes.0.4.opt.bc ./bcFileDir
cp ./src/chgrp.0.2.internalize.bc ./bcFileDir
cp ./src/date.0.4.opt.bc ./bcFileDir
cp ./src/[.0.0.preopt.bc ./bcFileDir
cp ./src/ginstall.0.4.opt.bc ./bcFileDir
cp ./src/rmdir.0.5.precodegen.bc ./bcFileDir
cp ./src/md5sum.0.0.preopt.bc ./bcFileDir
cp ./src/comm.0.2.internalize.bc ./bcFileDir
cp ./src/cp.0.4.opt.bc ./bcFileDir
cp ./src/unlink.0.0.preopt.bc ./bcFileDir
cp ./src/truncate.0.4.opt.bc ./bcFileDir
cp ./src/getlimits.0.2.internalize.bc ./bcFileDir
cp ./src/chmod.0.5.precodegen.bc ./bcFileDir
cp ./src/logname.0.5.precodegen.bc ./bcFileDir
cp ./src/sha1sum.0.5.precodegen.bc ./bcFileDir
cp ./src/runcon.0.2.internalize.bc ./bcFileDir
cp ./src/paste.0.2.internalize.bc ./bcFileDir
cp ./src/split.0.4.opt.bc ./bcFileDir
cp ./src/nice.0.2.internalize.bc ./bcFileDir
cp ./src/uname.0.5.precodegen.bc ./bcFileDir
cp ./src/head.0.0.preopt.bc ./bcFileDir
cp ./src/vdir.0.5.precodegen.bc ./bcFileDir
cp ./src/pwd.0.0.preopt.bc ./bcFileDir
cp ./src/sleep.0.0.preopt.bc ./bcFileDir
cp ./src/rm.0.2.internalize.bc ./bcFileDir
cp ./src/sort.0.2.internalize.bc ./bcFileDir
cp ./src/mktemp.0.2.internalize.bc ./bcFileDir
cp ./src/join.0.4.opt.bc ./bcFileDir
cp ./src/cp.0.5.precodegen.bc ./bcFileDir
cp ./src/dircolors.0.5.precodegen.bc ./bcFileDir
cp ./src/stat.0.5.precodegen.bc ./bcFileDir
cp ./src/shred.0.4.opt.bc ./bcFileDir
cp ./src/cat.0.4.opt.bc ./bcFileDir
cp ./src/pwd.0.2.internalize.bc ./bcFileDir
cp ./src/id.0.0.preopt.bc ./bcFileDir
cp ./src/expand.0.5.precodegen.bc ./bcFileDir
cp ./src/tr.0.2.internalize.bc ./bcFileDir
cp ./src/pathchk.0.2.internalize.bc ./bcFileDir
cp ./src/pr.0.2.internalize.bc ./bcFileDir
cp ./src/runcon.0.5.precodegen.bc ./bcFileDir
cp ./src/nohup.0.2.internalize.bc ./bcFileDir
cp ./src/factor.0.0.preopt.bc ./bcFileDir
cp ./src/nice.0.4.opt.bc ./bcFileDir
cp ./src/libstdbuf.so.0.0.preopt.bc ./bcFileDir
cp ./src/printf.0.0.preopt.bc ./bcFileDir
cp ./src/du.0.4.opt.bc ./bcFileDir
cp ./src/pwd.0.5.precodegen.bc ./bcFileDir
cp ./src/pwd.0.4.opt.bc ./bcFileDir
cp ./src/pathchk.0.5.precodegen.bc ./bcFileDir
cp ./src/runcon.0.0.preopt.bc ./bcFileDir
cp ./src/chown.0.5.precodegen.bc ./bcFileDir
cp ./src/tsort.0.4.opt.bc ./bcFileDir
cp ./src/pr.0.4.opt.bc ./bcFileDir
cp ./src/unexpand.0.2.internalize.bc ./bcFileDir
cp ./src/ln.0.2.internalize.bc ./bcFileDir
cp ./src/numfmt.0.0.preopt.bc ./bcFileDir
cp ./src/ptx.0.2.internalize.bc ./bcFileDir
cp ./src/sha384sum.0.0.preopt.bc ./bcFileDir
cp ./src/date.0.5.precodegen.bc ./bcFileDir
cp ./src/ptx.0.5.precodegen.bc ./bcFileDir
cp ./src/printf.0.4.opt.bc ./bcFileDir
cp ./src/stat.0.4.opt.bc ./bcFileDir
cp ./src/groups.0.2.internalize.bc ./bcFileDir
cp ./src/[.0.5.precodegen.bc ./bcFileDir
cp ./src/users.0.4.opt.bc ./bcFileDir
cp ./src/shuf.0.5.precodegen.bc ./bcFileDir
cp ./src/mv.0.5.precodegen.bc ./bcFileDir
cp ./src/sleep.0.4.opt.bc ./bcFileDir
cp ./src/uname.0.4.opt.bc ./bcFileDir
cp ./src/chcon.0.0.preopt.bc ./bcFileDir
cp ./src/env.0.5.precodegen.bc ./bcFileDir
cp ./src/numfmt.0.4.opt.bc ./bcFileDir
cp ./src/logname.0.4.opt.bc ./bcFileDir
cp ./src/rm.0.0.preopt.bc ./bcFileDir
cp ./src/mkfifo.0.0.preopt.bc ./bcFileDir
cp ./src/who.0.5.precodegen.bc ./bcFileDir
cp ./src/whoami.0.5.precodegen.bc ./bcFileDir
cp ./src/uname.0.2.internalize.bc ./bcFileDir
cp ./src/join.0.2.internalize.bc ./bcFileDir
cp ./src/whoami.0.2.internalize.bc ./bcFileDir
cp ./src/uptime.0.0.preopt.bc ./bcFileDir
cp ./src/touch.0.2.internalize.bc ./bcFileDir
cp ./src/wc.0.4.opt.bc ./bcFileDir
cp ./src/cksum.0.2.internalize.bc ./bcFileDir
cp ./src/stty.0.0.preopt.bc ./bcFileDir
cp ./src/realpath.0.2.internalize.bc ./bcFileDir
cp ./src/make-prime-list.0.4.opt.bc ./bcFileDir
cp ./src/mv.0.4.opt.bc ./bcFileDir
cp ./src/stdbuf.0.0.preopt.bc ./bcFileDir
cp ./src/cut.0.2.internalize.bc ./bcFileDir
cp ./src/tty.0.2.internalize.bc ./bcFileDir
cp ./src/tac.0.5.precodegen.bc ./bcFileDir
cp ./src/tee.0.4.opt.bc ./bcFileDir
cp ./src/cksum.0.4.opt.bc ./bcFileDir
cp ./src/tail.0.2.internalize.bc ./bcFileDir
cp ./src/yes.0.0.preopt.bc ./bcFileDir
cp ./src/base64.0.0.preopt.bc ./bcFileDir
cp ./src/cat.0.5.precodegen.bc ./bcFileDir
cp ./src/sync.0.0.preopt.bc ./bcFileDir
cp ./src/du.0.2.internalize.bc ./bcFileDir
cp ./src/tr.0.4.opt.bc ./bcFileDir
cp ./src/timeout.0.2.internalize.bc ./bcFileDir
cp ./src/true.0.0.preopt.bc ./bcFileDir
cp ./src/base64.0.5.precodegen.bc ./bcFileDir
cp ./src/unlink.0.2.internalize.bc ./bcFileDir
cp ./src/pinky.0.2.internalize.bc ./bcFileDir
cp ./src/getlimits.0.0.preopt.bc ./bcFileDir
cp ./src/chroot.0.4.opt.bc ./bcFileDir
cp ./src/head.0.5.precodegen.bc ./bcFileDir
cp ./src/pathchk.0.0.preopt.bc ./bcFileDir
cp ./src/rmdir.0.0.preopt.bc ./bcFileDir
cp ./src/hostid.0.5.precodegen.bc ./bcFileDir
cp ./src/link.0.2.internalize.bc ./bcFileDir
cp ./src/printenv.0.0.preopt.bc ./bcFileDir
cp ./src/tail.0.5.precodegen.bc ./bcFileDir
cp ./src/vdir.0.0.preopt.bc ./bcFileDir
cp ./src/expand.0.4.opt.bc ./bcFileDir
cp ./src/ls.0.5.precodegen.bc ./bcFileDir
cp ./src/ln.0.0.preopt.bc ./bcFileDir
cp ./src/tail.0.0.preopt.bc ./bcFileDir
cp ./src/df.0.0.preopt.bc ./bcFileDir
cp ./src/timeout.0.0.preopt.bc ./bcFileDir
cp ./src/tail.0.4.opt.bc ./bcFileDir
cp ./src/fold.0.2.internalize.bc ./bcFileDir
cp ./src/dir.0.5.precodegen.bc ./bcFileDir
cp ./src/mknod.0.5.precodegen.bc ./bcFileDir
cp ./src/shuf.0.2.internalize.bc ./bcFileDir
cp ./src/libstdbuf.so.0.5.precodegen.bc ./bcFileDir
cp ./src/chown.0.4.opt.bc ./bcFileDir
cp ./src/tac.0.0.preopt.bc ./bcFileDir
cp ./src/uniq.0.2.internalize.bc ./bcFileDir
cp ./src/ln.0.5.precodegen.bc ./bcFileDir
cp ./src/vdir.0.2.internalize.bc ./bcFileDir
cp ./src/pr.0.5.precodegen.bc ./bcFileDir
cp ./src/du.0.0.preopt.bc ./bcFileDir
cp ./src/ginstall.0.0.preopt.bc ./bcFileDir
cp ./src/paste.0.5.precodegen.bc ./bcFileDir
cp ./src/mknod.0.4.opt.bc ./bcFileDir
cp ./src/csplit.0.0.preopt.bc ./bcFileDir
cp ./src/chcon.0.5.precodegen.bc ./bcFileDir
cp ./src/dirname.0.5.precodegen.bc ./bcFileDir
cp ./src/nproc.0.0.preopt.bc ./bcFileDir
cp ./src/id.0.2.internalize.bc ./bcFileDir
cp ./src/test.0.4.opt.bc ./bcFileDir
cp ./src/sync.0.5.precodegen.bc ./bcFileDir
cp ./src/dd.0.2.internalize.bc ./bcFileDir
cp ./src/ls.0.2.internalize.bc ./bcFileDir
cp ./src/env.0.2.internalize.bc ./bcFileDir
cp ./src/md5sum.0.2.internalize.bc ./bcFileDir
cp ./src/uptime.0.4.opt.bc ./bcFileDir
cp ./src/od.0.0.preopt.bc ./bcFileDir
cp ./src/uniq.0.0.preopt.bc ./bcFileDir
cp ./src/basename.0.4.opt.bc ./bcFileDir
cp ./src/false.0.4.opt.bc ./bcFileDir
cp ./src/mv.0.0.preopt.bc ./bcFileDir
cp ./src/fmt.0.4.opt.bc ./bcFileDir
cp ./src/shuf.0.4.opt.bc ./bcFileDir
cp ./src/true.0.5.precodegen.bc ./bcFileDir
cp ./src/true.0.2.internalize.bc ./bcFileDir
cp ./src/nl.0.5.precodegen.bc ./bcFileDir
cp ./src/factor.0.2.internalize.bc ./bcFileDir
cp ./src/printf.0.5.precodegen.bc ./bcFileDir
cp ./src/kill.0.4.opt.bc ./bcFileDir
cp ./src/who.0.0.preopt.bc ./bcFileDir
cp ./src/expr.0.0.preopt.bc ./bcFileDir
cp ./src/libstdbuf.so.0.2.internalize.bc ./bcFileDir
cp ./src/join.0.5.precodegen.bc ./bcFileDir
cp ./src/runcon.0.4.opt.bc ./bcFileDir
cp ./src/chroot.0.2.internalize.bc ./bcFileDir
cp ./src/echo.0.2.internalize.bc ./bcFileDir
cp ./src/fold.0.5.precodegen.bc ./bcFileDir
cp ./src/comm.0.5.precodegen.bc ./bcFileDir
cp ./src/uniq.0.5.precodegen.bc ./bcFileDir
cp ./src/seq.0.4.opt.bc ./bcFileDir
cp ./src/groups.0.5.precodegen.bc ./bcFileDir
cp ./src/numfmt.0.2.internalize.bc ./bcFileDir
cp ./src/dirname.0.4.opt.bc ./bcFileDir
cp ./src/env.0.4.opt.bc ./bcFileDir
cp ./src/nice.0.5.precodegen.bc ./bcFileDir
cp ./src/fold.0.0.preopt.bc ./bcFileDir
cp ./src/sha1sum.0.4.opt.bc ./bcFileDir
cp ./src/nproc.0.4.opt.bc ./bcFileDir
cp ./src/sync.0.4.opt.bc ./bcFileDir
cp ./src/chmod.0.2.internalize.bc ./bcFileDir
cp ./src/cksum.0.0.preopt.bc ./bcFileDir
cp ./src/sha224sum.0.0.preopt.bc ./bcFileDir
cp ./src/tac.0.4.opt.bc ./bcFileDir
cp ./src/groups.0.0.preopt.bc ./bcFileDir
cp ./src/fmt.0.0.preopt.bc ./bcFileDir
cp ./src/timeout.0.5.precodegen.bc ./bcFileDir
cp ./src/tsort.0.0.preopt.bc ./bcFileDir
cp ./src/test.0.5.precodegen.bc ./bcFileDir
cp ./src/sha384sum.0.2.internalize.bc ./bcFileDir
cp ./src/unlink.0.5.precodegen.bc ./bcFileDir
cp ./src/hostid.0.2.internalize.bc ./bcFileDir
cp ./src/od.0.4.opt.bc ./bcFileDir
cp ./src/kill.0.0.preopt.bc ./bcFileDir
cp ./src/rm.0.5.precodegen.bc ./bcFileDir
cp ./src/nl.0.4.opt.bc ./bcFileDir
cp ./src/timeout.0.4.opt.bc ./bcFileDir
cp ./src/libstdbuf.so.0.4.opt.bc ./bcFileDir
cp ./src/dircolors.0.4.opt.bc ./bcFileDir
cp ./src/printf.0.2.internalize.bc ./bcFileDir
cp ./src/link.0.0.preopt.bc ./bcFileDir
cp ./src/expr.0.2.internalize.bc ./bcFileDir
cp ./src/sum.0.5.precodegen.bc ./bcFileDir
cp ./src/fmt.0.5.precodegen.bc ./bcFileDir
cp ./src/base64.0.2.internalize.bc ./bcFileDir
cp ./src/dirname.0.0.preopt.bc ./bcFileDir
cp ./src/date.0.0.preopt.bc ./bcFileDir
cp ./src/rm.0.4.opt.bc ./bcFileDir
cp ./src/mknod.0.0.preopt.bc ./bcFileDir
cp ./src/kill.0.2.internalize.bc ./bcFileDir
cp ./src/chroot.0.5.precodegen.bc ./bcFileDir
cp ./src/unlink.0.4.opt.bc ./bcFileDir
cp ./src/chmod.0.4.opt.bc ./bcFileDir
cp ./src/mknod.0.2.internalize.bc ./bcFileDir
cp ./src/date.0.2.internalize.bc ./bcFileDir
cp ./src/truncate.0.0.preopt.bc ./bcFileDir
cp ./src/sync.0.2.internalize.bc ./bcFileDir
cp ./src/vdir.0.4.opt.bc ./bcFileDir
cp ./src/sha256sum.0.2.internalize.bc ./bcFileDir
cp ./src/rmdir.0.2.internalize.bc ./bcFileDir
cp ./src/ls.0.4.opt.bc ./bcFileDir
cp ./src/basename.0.2.internalize.bc ./bcFileDir
cp ./src/whoami.0.4.opt.bc ./bcFileDir
cp ./src/split.0.2.internalize.bc ./bcFileDir
cp ./src/sha256sum.0.5.precodegen.bc ./bcFileDir
cp ./src/expand.0.0.preopt.bc ./bcFileDir
cp ./src/cut.0.0.preopt.bc ./bcFileDir
cp ./src/ln.0.4.opt.bc ./bcFileDir
cp ./src/stty.0.4.opt.bc ./bcFileDir
cp ./src/nohup.0.0.preopt.bc ./bcFileDir
cp ./src/nohup.0.4.opt.bc ./bcFileDir
cp ./src/sum.0.4.opt.bc ./bcFileDir
cp ./src/tsort.0.2.internalize.bc ./bcFileDir
cp ./src/logname.0.2.internalize.bc ./bcFileDir
cp ./src/true.0.4.opt.bc ./bcFileDir
cp ./src/df.0.2.internalize.bc ./bcFileDir
cp ./src/test.0.2.internalize.bc ./bcFileDir
cp ./src/shred.0.2.internalize.bc ./bcFileDir
cp ./src/[.0.2.internalize.bc ./bcFileDir
cp ./src/sum.0.0.preopt.bc ./bcFileDir
cp ./src/readlink.0.2.internalize.bc ./bcFileDir
cp ./src/dd.0.4.opt.bc ./bcFileDir
cp ./src/head.0.4.opt.bc ./bcFileDir
cp ./src/sort.0.5.precodegen.bc ./bcFileDir
cp ./src/printenv.0.2.internalize.bc ./bcFileDir
cp ./src/getlimits.0.4.opt.bc ./bcFileDir
cp ./src/tty.0.4.opt.bc ./bcFileDir
cp ./src/sha1sum.0.0.preopt.bc ./bcFileDir
cp ./src/pinky.0.5.precodegen.bc ./bcFileDir
cp ./src/comm.0.0.preopt.bc ./bcFileDir
cp ./src/nproc.0.5.precodegen.bc ./bcFileDir
cp ./src/cat.0.0.preopt.bc ./bcFileDir
